### ISSUE TITLE
Remove node_modules folder

### ISSUE THREAD

**Issue by rntsza** [lcnsilva/gerenciabikeapi#3]
The node_modules folder can be quite large, as it contains all the packages installed for your project. 
Including it in your Git repository can make cloning and pulling operations very slow, and increase the repository size unnecessarily, and often, there’s no need to track changes in these files as they’re managed by your package manager.

Remove this folder from source code

Added from #1

**Comment by lcnsilva** [comment]
node_modules removed, thanks.
